nusskylab/nusskylab

app/helpers/students_helper.rb
app/views/students/_students_table.html.erb

- Add sortable dropped column
- Strike out team name if dropped
- Strike out student name if dropped
1 hour

Modify view for student listing to show team dropped status

---

app/assets/javascripts/application.js

#514
This removes the console error "autolink is not a function" and fixes the buttons in survey templates.
There was already another jquery import statement in the first line of the file and this seems to be repeated. Similarly for the bootstrap file.
I did not remove all of them since I did not know if I would break anything, so for now I only removed the one that caused this bug. Hopefully this fixes the issue.

Fix buttons

---

app/views/students/_students_table.html.erb

This allows admin to see when student registered.
Partially resolves #527, but sort functionality has yet to be implemented (still investigating why tables are not displaying sort arrows). Merge now if @zhaojin42 requires. Thanks!

Add view in students table displaying registration date and time.

---

app/models/student.rb
db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb
db/migrate/20170307175911_remove_moderation_functionality.rb
spec/models/students_spec.rb

Student data csv will now display the registration date.

Allow all user csv downloads to have a 'registered on' column. (#527)

---

app/views/submissions/_submission_form.html.erb

Try with Project Log extended description first.

Show submission instructions 540

---

app/views/users/show.html.erb

Close registration in the users page by removing the button.

---

app/controllers/evaluatings_controller.rb

Address issue #546, tested locally. Old LoC has been commented out in case revert is needed in the future.

Allow advisors to CRUD evaluation relations for all teams. (#546)

---

app/controllers/admins_controller.rb
app/helpers/admins_helper.rb
app/helpers/users_helper.rb
app/views/admins/_admin_view.html.erb
app/views/users/show.html.erb
config/routes.rb

Added button to allow admin users to toggle the registration status.
For this to work, a new environment variable needs to be initialized. To do this, enter the following command into vagrant ssh `declare -x REGISTRATION_STATUS="closed"`
We are currently working on adding the command to bootstrap.sh

Add Button to turn on and off registration

---

app/controllers/users_controller.rb
app/views/teams/_team_form.html.erb

Fixes #556.
Also updates the default level of achievement for new teams to "Project Gemini".

Fix: "Edit team" page should use the actual LoA instead of the default value "Vostok"

---

test/fixtures/admins.yml
test/fixtures/advisers.yml
test/fixtures/students.yml
test/fixtures/users.yml

resolve #560 
add fixture data
to load db with fixture data
```
bundle exec rake db:fixtures:load RAILS_ENV="development"
```
database is now populated with fixture data
Shows up under "Users and roles" tab
these are the guides I used
<a href="http://guides.rubyonrails.org/testing.html"> ROR Testing guide </a>
<a href="http://api.rubyonrails.org/v5.1.5/classes/ActiveRecord/FixtureSet.html">ROR fixture api</a>
<a href="http://www.seanbehan.com/rails-fixtures-using-the-right-timestamp/"> Loading fixture and timestamp</a>
<a href="http://api.rubyonrails.org/classes/Time.html#method-i-to_s"> Time api</a>

Fixture data

---

db/migrate/20180319190421_add_slide_link_to_mentors.rb
db/migrate/20180424185500_add_slide_link_to_teams.rb
db/migrate/20180424190355_add_video_link_to_teams.rb
db/schema.rb

Add slide and video link to mentors table

---

db/migrate/20180424185500_add_slide_link_to_teams.rb
db/migrate/20180424190355_add_video_link_to_teams.rb
db/schema.rb

Fixes migration errors caused by duplicate migrations.

Fix migration

---

app/assets/javascripts/public_views/group_carousel.js
app/assets/stylesheets/public_views/3-col-portfolio.css
app/controllers/public_views/group_carousel_controller.rb
app/views/public_views/group_carousel/index.html.erb
app/views/public_views/public_staff/_user_roles.html.erb
config/routes.rb

#579 carousel to populate team slide link for each advisers

---

app/controllers/public_views/mentor_slides_controller.rb
app/views/public_views/mentor_slides/index.html.erb
app/views/public_views/public_staff/_user_roles.html.erb
config/routes.rb
test/fixtures/mentors.yml
test/fixtures/users.yml

1. the button is right under the mentors header
2. it displays all the mentors slides dynamically (means if the slide varies in size, the carousel changes with it, not sure if this is a good idea)
3. it will only populate mentors with name and link, so if the mentors have no link updated, his or her info will not be found in the carousel

#582 carousel for mentors

---

app/controllers/mentors_controller.rb
app/views/mentors/_mentor_form.html.erb
app/views/mentors/_mentors_table.html.erb
config/locales/en.yml
config/routes.rb

Allows mentors to be edited from the frontend. At the moment, it only allows editing of slide links.

Feature: add ability to edit mentors

---

app/views/mentors/edit.html.erb

Fixes a missing edit page from the previous PR.

fix missing edit page

---

app/controllers/cohort_helper.rb

#576 Update install to current 2018 year.

---

app/models/team.rb
spec/models/teams_spec.rb

Fixes #601. Also adds in the missing "is_pending" field to the exported information.

#601 Export poster and video links from Skylab

---

app/views/submissions/_submission_details.html.erb

#623 Display poster link when the Milestone submission is viewed

---

app/helpers/teams_helper.rb
app/models/team.rb
app/views/teams/_teams_table.html.erb
spec/models/teams_spec.rb

Fixes #550 
I used my own fixture data for this and will be adding it to the fixtures in #632
Add columns for submission status
Update to_csv to include submission status
Write rspec tests for the new methods
PR Is ready for code review

Page to see milestone submisions for teams

---

app/helpers/submissions_helper.rb
app/views/submissions/_submissions_display.html.erb
app/views/submissions/index.html.erb

Stop the page from crashing - DONE
FIx team rendering issue - DONE
Fix modal box - DONE
Render the Submissions in tabs inside the modal  - DONE
Make each tab render only one submission - DONE

Fix all-teams page view 

---

.travis.yml
Gemfile
Gemfile.lock
server.sh
servernopull.sh

Updated gems to latest minor version - DONE
Fixed Omniauth Hashie warning - DONE
Before:
After:
Issues referenced:
1. https://github.com/omniauth/omniauth/issues/872
1. https://github.com/intridea/hashie/issues/391
Update Ruby version from 2.2.1 to 2.3.3 in config files - DONE

Update Ruby version in config and gems june 2018

---

test/fixtures/milestones.yml
test/fixtures/students.yml
test/fixtures/teams.yml

#555 
adding fixtures for teams, one team with advisor another without advisor
##Previewing as student 10, in team id:1801 with advisor
Clicked on submit feedback
</br>
result:
Note: milestones not set yet
</br>
After creating Milestone 3
and  clicking on `submit feedback` for advisors button
##Previewing as student 11, no advisor
click on submit feedback

Evaluating advisors fixture

---

app/controllers/peer_evaluations_controller.rb
app/controllers/submissions_controller.rb
test/fixtures/admins.yml
test/fixtures/advisers.yml
test/fixtures/evaluatings.yml
test/fixtures/mentors.yml
test/fixtures/milestones.yml
test/fixtures/peer_evaluations.yml
test/fixtures/questions.yml
test/fixtures/students.yml
test/fixtures/submissions.yml
test/fixtures/survey_templates.yml
test/fixtures/teams.yml
test/fixtures/users.yml

**READY**
NO
The path permissions issue is due to some checks not being to done to ensure `current_user` has sufficient rights. 
1. Re-initialize fixtures. 
2. Log in as user1713 (this user has the team of 1732. This team has submission id of 1747.)
3. Test for authorized access: http://0.0.0.0:3000/milestones/1/teams/1732/submissions/1747/edit
4. Test for unauthorized access: http://0.0.0.0:3000/milestones/1/teams/1732/submissions/1746/edit
1. Re-initialize fixtures. 
2. Log in as user1713
3. Test for authorized access: http://0.0.0.0:3000/milestones/3/teams/1732/peer_evaluations/1/edit
4. Test for unauthorized access: http://0.0.0.0:3000/milestones/3/teams/1732/peer_evaluations/2/edit

Fix path permissions

---

app/controllers/cohort_helper.rb

**READY**
NO
Add 2019 project page. Resolve #669.

Add 2019 project page

---

app/views/feedbacks/_feedback_form.html.erb
app/views/survey_templates/_survey_template_view.html.erb

**IN DEVELOPMENT**
NO
I have added checks for nil conditions in the feedback form and survey template views as I was getting errors when creating them respectively. Working on #640

Update feedback form

---

app/views/users/register_as_student.html.erb

**READY**
NO
I added a check for the status of registration in the embedded ruby file. Resolves #672

Disable registration URL

---

app/views/teams/_teams_table.html.erb

**READY**
NO
Before change:
After change:
1. [Strange button at the Teams page](https://github.com/nusskylab/nusskylab/issues/701)
2. [Reorganize the Teams page](https://github.com/nusskylab/nusskylab/issues/666)
1. [Reorganize Teams page](https://github.com/nusskylab/nusskylab/pull/688)

Add button to view submission directly

---

app/controllers/submissions_controller.rb

**READY**
NO
Fix #706. #707 will be fixed in a separate PR.

Allow advisor and peer teams to view submission to be evaluated

---

.gitignore
app/controllers/peer_evaluations_controller.rb
app/views/teams/_teams_table.html.erb
app/views/teams/index.html.erb

**READY**
NO
Update the UI for the teams page by making table columns wider and the team panel width same as the table width

Modify Teams Page UI

---

app/assets/stylesheets/teams.scss
app/controllers/teams_controller.rb
app/models/team.rb
app/views/teams/_team_basic_info.html.erb
app/views/teams/_team_form.html.erb
app/views/teams/_teams_table.html.erb
app/views/teams/index.html.erb
config/initializers/assets.rb
db/migrate/20190604024654_add_status_details_to_teams.rb
db/schema.rb

**In-Development**
YES
Included a status column. 
* Good => Contactable and doing well
* OK => Contactable but lack progress
* Poor => Uncontactable
* TBR => To be re-evaluated
Added fields for status and comments under edit team's page (accessible by advisers and admin)
NIL
Run migrations
New teams page.
Team edit page.
fixes #703 
*

feature to update team status

---

app/models/team.rb
spec/models/teams_spec.rb

**READY**
NO
Realised that the problem is with the use of the wrong get submission method.
Added team status and comments to CSV as well
#696 
#713  
*

Replace incorrect method

---

app/controllers/peer_evaluations_controller.rb

Adding line change as per discussion in #733 
Fixes #733

Update params to find correct submission

---

.gitignore
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/mentors_new_batch.js
app/assets/stylesheets/application.scss
app/controllers/admins_controller.rb
app/controllers/advisers_controller.rb
app/controllers/facilitators_controller.rb
app/controllers/mentors_controller.rb
app/controllers/roles_controller.rb
app/controllers/students_controller.rb
app/controllers/tutors_controller.rb
app/views/admins/index.html.erb
app/views/admins/new_batch.erb
app/views/advisers/index.html.erb
app/views/advisers/new_batch.erb
app/views/facilitators/index.html.erb
app/views/facilitators/new_batch.erb
app/views/mentors/_new_batch_mentors_form.html.erb
app/views/mentors/index.html.erb
app/views/mentors/new_batch.erb
app/views/students/index.html.erb
app/views/students/new_batch.erb
app/views/tutors/index.html.erb
app/views/tutors/new_batch.erb
config/environments/production.rb
config/locales/en.yml
config/routes.rb

**READY**
NO
Resolve #663. Batch creation of roles through multi-selection.
1. Run `bundle install` to install the new `bootstrap-select-rails` gem. 
2. Log in as admin.
3. Go to /{{role_to_test}}/new_batch. OR Go to the `index` page of the roles you want to test, then click on `Create new {{role_to_test}}` button.

Add batch creation of role

---

.github/pull_request_template.md

I am adding another section for developers to upload screenshots to highlight UI changes in the future.

Add screenshot section to the Pull Request template

---

app/controllers/submissions_controller.rb
config/locales/en.yml

**READY**
NO
I have modified the YAML file used for configuring the I18n Rails module. These changes get directly translated to the content rendered on the web pages.
Resolves #732

Update page titles

---

app/views/public_views/public_projects/_public_teams_table.html.erb

**READY**
NO
Display the team id in the project gallery and change the header to bold
* Close #835

Show team id and change formatting in project gallery

---

config/database.yml

YES | NO
See linked issue for full message
*

fix pg error when running bundle install on vagrant

---

app/assets/stylesheets/public_views/3-col-portfolio.css
app/views/public_views/public_projects/_public_teams_table.html.erb

YES | NO
A few sentences describing the overall goals of the pull request's commits.
Add 2 buttons to show poster and video links
Add screenshot showing the current state of Skylab (in sync with the master branch)
*

! Attempt to add link

---

Gemfile

YES | NO
Rails SSL certificate expired.
Add screenshots to [summarize the UI changes (if any)]
*

Change rails source

---

app/models/team.rb
app/views/teams/_team_form.html.erb

**READY**
NO
Admin can change project level even when locked.
Advisers can change project level when unlocked and team is not artemis level. Cannot upgrade team to artemis level.
Mentors and students cannot change project level at all.
When locked no one can change level.
As admin,
When unlocked:
- Mentor can change team level.
- Adviser can change team level.
- Student can change team level.
When locked, admin can change project level.
When unlocked:
- Adviser cannot change artemis level teams.
- Adviser can change lower tier teams.
- Mentor cannot change project level.
- Student cannot change project level.
Outline the steps to test or reproduce the …

LoA locking
