app/controllers/submissions_controller.rb
Fixes #476 
Upon failed submission due to empty user input field(s), render page instead of redirecting
=> Retain submission form data when submitting with empty user input fields

app/models/team.rb
#460 and #461 is fixed easily by adding in a nil check for evaluation.private_content
Might be due to evaluators not giving a rating to the team yet/dropped orbital?
However I am not sure of the proper format of creating a evaluation template with rating score style questions to test if the rating calculation feature still works.
=> Evaluation ratings related bugs

app/controllers/users_controller.rb, app/models/user.rb, app/views/shared/nav_headers/_admin_nav_header_list.html.erb, app/views/shared/nav_headers/_adviser_nav_header_list.html.erb, config/initializers/devise.rb, config/secrets.yml.travis
1. Add a link in the nav bar for for admins and advisors as the other user types use the general nav header.
2. Update the user fields to add Matric Number and Home Faculty fields. 
Implement a validation check for Matric Numbers. 
Matric number can be left blank for mentors etc.
=> Add link into Nav bar and check for matric number validity

app/views/peer_evaluations/_peer_evaluation_form.html.erb
Fixes #494
On default button press opens peer submission in new tab.
Added instructions on dragging it into split view for easier reference.
=> Open peer submission in new tab

app/assets/stylesheets/public_views/3-col-portfolio.css, app/assets/stylesheets/submissions/thumbnail-gallery.css
Fixes #511
Not sure why padding-top was set to 70px all along, because we are not using .navbar-fixed-top
=> Fix navbar position

config/initializers/thredded.rb, db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb, db/migrate/20170307175911_remove_moderation_functionality.rb, db/schema.rb
_Discussion here distills instructions from preceding comments in PRs and issues_
Note: Before performing the merge, check whether the following line in `config/initializers/thredded.rb` matches this:
> ```
>12: Thredded.user_name_column = :user_name
>```
If not, perform a `git pull` from master and ignore the conflict in this file only.
---
And then, or otherwise: 
To overcome this, reference the user's id `@1`, for example.
Currently, an error message is posted upon hitting the post button, which would be because of this:
`A copy of XX has been removed from the module tree but is still active!`
It should be solved with restarting the rails app **after merging this PR**. Basically the app was not restarted during the last `git pull`, where Thredded was first introduced. **Anytime we make …
=> Fix notifications (#520, #521)

app/controllers/application_controller.rb, config/initializers/thredded.rb
- Registered users (including pending students) can now access the forum. (fixed #522)
- Disabled email notification system until sendgrid issue is looked into. Users no longer face the RSOD when they hit reply/post. (NOTE: Private messaging still does not work)
Remember to restart rails since `thredded.rb` was modified.
Cheers ~
=> Allow all registered users to access forums (#522)

db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb, db/migrate/20170307175911_remove_moderation_functionality.rb
Issued due to errors from #530 and #526.
These migrations fail to run on our existing database. This is because 
1) our users table already has an index 
2) there exist duplicate names in the db, so unique index cannot be generated.
To fix this we will first remove these two migration files. No need to rollback because the migration failed in the first place (correct me if I am wrong) and nothing happened to the db. After pulling it would be prudent to perform a rollback: 
```
(bundle exec) rake db:migrate:down VERSION=20161230033247
(bundle exec) rake db:migrate
```
Thanks!
=> Remove db:migration files that are causing migration errors.

config/initializers/thredded.rb
Addresses issue #532.
The logs still indicate `Thredded::Notifier` is being called. Uncommented a line in `config/initializers/thredded.rb` which would force it to not be called.
Let's test this out and see if the error resolves. See how from there, thanks!
=> Remove Thredded notifications for good.

config/initializers/thredded.rb, db/migrate/20170307170913_add_index_to_username_in_users_for_thredded.rb, db/migrate/20170307175911_remove_moderation_functionality.rb, db/schema.rb
This PR does the following
- Reactivate notification system, but with
- From email parameters and
- Subject header email parameters set
- Force off auto follow of topics and posts, because that is the nature of the error.
If this fails we will post up our issue to the Thredded issue tracker and see how it goes. Thanks!
=> Fix forum notifications, part 2

app/views/questions/_text_question.html.erb
Addresses #548.
In `app/views/questions/_text_question.html.erb`, I have changed `<div class="form-control-static" ...` to `<textarea class="form-control" readonly="true" ... ` to enable line breaks.
This implies that **all** answers to text questions in view mode (e.g. View Peer Evaluation, View Submission) are rendered as read-only text boxes, which preserves line breaks. Note that text questions do not support formatting.
=> Enable line breaks for peer evaluation response viewing.

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
Fixes #574
Fixes this issue by setting `margin` property to 0 only for the main footer element.
=> Fix: remove margins in main footer element

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Addresses missing backend logic for #554. While buttons do link up correctly from that PR, the controller currently does not allow confirmed students to use those links.
=> Fix: show an invite button to registered students without teams

app/views/mentors/_mentor_view.html.erb, app/views/mentors/_mentors_teams.html.erb
In reference to Issue #571 
* Allow mentors to view profiles of teams assigned to them
* Allowing mentors to view submitted milestones was already implemented, I did test it and it works well
=> Allow mentors to view the team profiles of teams assigned to them

app/controllers/admins_controller.rb, app/helpers/admins_helper.rb, app/views/admins/_admin_view.html.erb, app/views/teams/_team_form.html.erb, config/routes.rb
Solves issue #557
Add feature to freeze and unfreeze level of achievement. Implementation is similar to #585 and also requires a new environment variable to be set using `declare -x PROJECT_LEVEL_SWAP_STATUS="locked"`
=> Feature to Lock/Unlock project level

app/assets/stylesheets/public_views/3-col-portfolio.css, app/views/public_views/group_carousel/index.html.erb, app/views/public_views/mentor_slides/index.html.erb
Fixes #619 
Also refactored some code in the carousel. No change to the end product on the page.
Used a class name called `info` to style it, not sure if there is any other names...
=> Carousel: fix the h5 styling by adding a separate class

app/assets/stylesheets/public_views/3-col-portfolio.css, app/views/public_views/public_projects/_public_teams_table.html.erb, app/views/public_views/public_projects/index.html.erb, test/fixtures/students.yml, test/fixtures/teams.yml, test/fixtures/users.yml
Fixes #626 
In each of the teams under public projects tab, show the poster image teams submitted for milestone0 instead of merely team icons.
If there is no poster link submitted, the image will show a default icon as shown below. On top of that, the poster images populated for each team is clickable to link them to see a bigger version of the image. 
However, the only issue is that if it is not a poster_link that ends with image tag, it does not show anything. Not sure how to fix this yet.
=> #626 Public Projects to show individual team's poster instead of merely icons

app/controllers/students_controller.rb, app/models/team.rb, app/views/students/_student_submit_feedbacks.html.erb, app/views/students/_student_with_team.html.erb, test/fixtures/students.yml, test/fixtures/teams.yml
Fixes #555 
Following the fixture data below. I managed to reproduce the problem on local.
It seems that the first time a student submit the feedback to the advisor, it works with a successful message. Thereafter, the second attempt the user tries to create the feedback, the advisor will receive an error message. (The 23 seconds gif below explains this situation)
Upon submitting the feedback initially, the data submitted is saved in the database as shown below. Hence, there is an error message when the user tries to save again.
I believe that the second time the user should see `Edit Feedback` instead of `Submit Feedback` as the feedback is already created in the database in the first attempt. That is why only some teams face this problem of not being able to save and demo team has no …
=> #555 unable to give feedback to advisors

app/models/team.rb, test/fixtures/advisers.yml
Fixes #555 
Upon looking at the data files online, it seems that the adviser `user_id` is different from `id` shown in the image below. However, in the fixture data, user_id is same as id causing the difference in the problem.
Hence I tried to differentiate the user_id and id for adviser in local server and production server. It can be solved by simply using `id` instead of `user_id` to find the feedback.
It will show `Edit feedback` instead of `Create feedback now`
=> #555 student cannot give feedback to advisers

test/fixtures/advisers.yml
Steps to reproduce the bug if you are not on this branch:
1) Re-initialize fixtures.
2) Go to 'projects' page.
3) It should display an error page stating that `adviser.user` is of NIL Class.
This is caused by user_id in adviser.yml pointing to non-existent user. Let me know if there are any issues!
Also I am not sure whether to make a PR to `master` or to `dev` branch. Do advise!
=> Fix advisers.yml

app/views/public_views/public_projects/_public_teams_table.html.erb
Fix #647
I change the image filename from Vostok_Icon.png to Vostok_Icon.jpg as the assets image is kept as jpg instead of png.
Below are the screenshot to show that it is working on earlier cohorts
=> Fix missing default image for ealier cohorts under Vostok

app/assets/stylesheets/public_views/3-col-portfolio.css, app/views/public_views/public_projects/_public_teams_table.html.erb, test/fixtures/submissions.yml
Fixes #609.
Behaviour shown below:
=> #609 Project past teams modal in a better format

app/views/public_views/public_projects/_public_teams_table.html.erb
Fixes #634 
This is due to bootstrap not aligning properly caused by floating point error. More information for the fix can be found here https://stackoverflow.com/questions/22866109/bootstrap-columns-not-aligning-correctly
There is not enough data to ensure a complete fix. But after trying the current method. This is the before and after of the teams. Need @chowyb to double check on the server
Before:
After:
=> #634 Fix layout order for team projects

app/assets/javascripts/public_projects.js, app/views/public_views/public_projects/_public_teams_table.html.erb
Fix #664. This is a continuation of the previous PR: https://github.com/nusskylab/nusskylab/pull/668
**READY**
NO
Change the position of the javascript function createModalBox to the head instead of at the bottom of the body.
(Update: After looking at the production server, I realised that chrome security policy does not allow inline javascript. So, I translate from removing inline javascript to put at the head)
(Update 2: As the bug still persist, I transferred the javascript code to a javascript file.)
Read this: https://developer.chrome.com/extensions/contentSecurityPolicy#JSExecution.
1. Select Projects at the navigation bar.
2. Click on any team button.
3. You should be able to see the modal box as below.
=> Migrate javascript code to public_project.js

app/views/public_views/public_staff/index.html.erb, db/migrate/20190506181849_add_display_order_to_facilitators.rb, db/schema.rb
PENDING REVIEW
YES
Adds a new column 'display_order' to the facilitators table. The facilitators table is then reordered by the 'display_order' column, from smallest to biggest. The default display_order value is 0.
Run `bundle exec rails db:migrate`, then update a facilitator's display_order to a negative number and it should move to the top.
I was unable to load the fixture data in as described in the [wiki](https://github.com/nusskylab/nusskylab/wiki/Fixture-data), so I haven't been able to test it on existing data. I have only tested it on my manually entered data via adding new users and promoting them to facilitators.
Here is a [pastebin](https://pastebin.com/0N868n1G) of the full trace after running the fixture loading command
* #517 Reordering entries on the staff page
=> #517 reorder staff entries

app/controllers/teams_controller.rb, app/views/teams/show.html.erb
**READY**
NO
Fixes the bug raised in https://github.com/nusskylab/nusskylab/issues/682. The bug was cause when the locals that were needed to render `students/student_submit_feedbacks` was updated but was not reflected in `teams\show`. The bug was fix by updating the locals passed in when `students/student_submit_feedbacks` was rendered in `teams\show`
Students are now able to access the teams page
--
--
1. Login in as an admin
2. Got to `Users and Roles>Users` on the navbar on top
3. Select `Preview as` from any of the students that whose name follows the format `17XX`
4. Under the `User Roles` tab, select `A student`
5. Click on the team name of the student as shown below:
--
=> Fixes students being unable to view team page

app/models/student.rb, spec/controllers/students_controller_spec.rb
**READY**
NO
This commit cascades student deletion to delete the team that the student is in. These are the example images:
Deleting the second last user, name21 that belongs to team 1740, will cascade the deletion to the team without deleting his partner user, name1719:
The team is also deleted from the team tab:
I have also added tests for this functionality. My tests verify that 1. the team is deleted and 2. the second student still exists and have its team set to nil i.e. no team
https://github.com/nusskylab/nusskylab/issues/679
-
Delete a student from the Student table. Ensure that the student belongs to a team to see the desired effect.
=> Cascade student deletion

app/assets/javascripts/public_projects.js, app/models/team.rb, app/views/public_views/public_projects/_public_teams_table.html.erb
**READY**
NO
Resolves issue #656. On error of image tag, calls replaceImg(project_level) which replaces image of the team by the project level image. 
Replace #658 as this PR used a inefficient method. 
NIL
Before:
After:
*
=> Replace team image if not found

app/views/users/register_as_student.html.erb
**READY**
NO
Resolve #686 
Allow admin to view the submitted registration forms even when registration closes.
Before:
After:
=> Allow admin to view reg form

app/views/public_views/group_carousel/index.html.erb
**READY**
NO
Previous ERB code adds class="active" into carousel element if image index is 0. If the image at index 0 is blank, this will not be done and the first element of carousel does not have the active class and carousel will not work. 
Added a counter to count for the number of images that is blank prior to the first non blank image and set class="active" at index-counter=0.  
None
None
Fixes #693 
*
=> Fix carousel if first image is not found

app/assets/javascripts/submissions.js, app/views/teams/_teams_table.html.erb, app/views/teams/index.html.erb
**READY**
NO
- Adds new columns 'Student 1' and 'Student 2' with team member names if the names are in the database, otherwise the values filled in the respective columns are empty strings
- Adds buttons for poster and video links respectively if the status of submission is 'Submitted'
Issue #666 
Current Teams page: 
Teams page after modifications in the PR:
=> Reorganise Teams page

app/controllers/peer_evaluations_controller.rb, app/controllers/submissions_controller.rb
**READY**
NO
Refactor permission fixes and fix #707.
The main issue was that users are able to manipulate the URL such that they can "disguise" as team members from another team and view their submission/peer-evaluation. So the way it was fix was to check the permissions based on the submission/peer-evaluation's id. And from there, we obtain the authorized team and authorized set of users. Instead of just relying on the URL to determine the team.
=> Refactor permission fixes and fix #707

app/controllers/evaluatings_controller.rb, app/views/evaluatings/_evaluating_form.html.erb, app/views/evaluatings/new.html.erb
**READY**
NO
Filters the teams in drop down box by advisor when creating new evaluating relationship. This will reduce the effort required to scroll down the whole list of teams. It's a simple fix for #702
1. Sign in to NUSSkylab as admin
2. Go to the [users page](https://nusskylab-dev.comp.nus.edu.sg/users) and preview as an adviser 
(based on user name of an adviser in the [advisers page](https://nusskylab- 
dev.comp.nus.edu.sg/advisers))
3. On the [home page](https://nusskylab-dev.comp.nus.edu.sg/users/xxx), select the user roles tab 
and click on the 'An Adviser' button under the heading 'Use Skylab as: '
4. Go to the [Evaluatings page](https://nusskylab-dev.comp.nus.edu.sg/evaluatings) and click on the 
'Create New Evaluation Relationship' button
5. Compare the teams in the drop down …
=> Filter teams in dropdown box

app/views/users/show.html.erb
**READY**
NO
I have changed made slight modifications to the if and else conditions used in the show embedded Ruby file in views/user so that if a user is both an adviser and an admin, then there are both buttons shown side-by-side in the 'User Roles' tab within the home page.
#719
=> Add extra button in user roles section for admins who are advisers

app/views/advisers/_adviser_teams.html.erb, app/views/advisers/show.html.erb
Signed-off-by: Aadit <aadit.k12@gmail.com>
**READY**
NO
Replaces the **Evaluated teams** column of the table on the **View all your teams** tab of the adviser home page with multiple columns, one for each milestone. In each column, there is a button for each team evaluated linking to the peer evaluation for that milestone (if there is no peer evaluation for the team, then the button is grayed out).
Before:
After: 
Resolves #720
=> Display peer evaluations of each team in adviser home page

spec/spec_helper.rb
**READY**
NO
Reset the FactoryGirl Database state between each run. From the image below, I printed out the created team ids. We see that for each run, the created ids are dependent on the test run, this might create some issues in the future, since it is unintended
After fixing, we see that the created team ids are the same across test runs. 
I think this is a necessary fix because there might be some carryover states from previous runs. This means that the state of each test can possibly be different, and allow some bugs to slip through. 
-
Comment out the added code and print out the team ids of any one of the teams created in teams_rspec.db. Then add the code back in then test again. 
*
=> add db cleaner to reset db state between tests

app/models/team.rb, spec/models/teams_spec.rb, spec/spec_helper.rb
**READY**
NO
Refer to https://github.com/nusskylab/nusskylab/issues/680.
Validate team name to ensure that team name does not contain all numeric characters. I tried to allow for team id to be an exception. However, there are some test cases which are abit hard to avoid, and will still create bugs. Hence, it rejects all team names that are purely numbers. I created a custom validator rather than using the format way of validation so that more restrictions can be added in the future.  
I think we may need to change the default name for each team so that new teams can be created using the default id. 
The tests should be sufficient. Can also edit team names to numeric names and it should not work. 
*
=> Team name validation 

app/views/advisers/_adviser_teams.html.erb
**READY**
NO
There was a [missing milestone id check](https://github.com/nusskylab/nusskylab/pull/727/files#r298233410) that led to the Milestone 1 peer submission being shown in all the 3 columns for each team. Attached are the screenshots for one of the advisers in my mock data, before and after the change:
<h3>Before the change: </h3>
<h3>After the change:</h3>
In this set of test data, I have created peer evaluations for Milestone 1, 2 and 3 submissions of team `I am Team 1733` and for Milestone 1 submissions of teams `1717` and `I am team 1736`. Earlier, the uncreated peer evaluations were not grayed out but now those that have not been created are grayed out and the buttons link to the submissions of the respective team for the correct milestone.
The other lines of code changes are …
=> Fix error in peer submissions link on the advisor home page

app/models/submission.rb, app/views/submissions/_submissions_display.html.erb
added function to get milestone number from milestone_number attribute in Submissions model
**READY**
NO
Milestone number was retrieved from milestone id, which is default incremental from the db. Added a function to get the number from the milestone_number attribute in Submissions table introduced in PR #696 
PR #696 
NIL
Go to All Teams page, click on team's name
Closes #730 
*
=> Corrected milestone number in all teams page

app/views/teams/_teams_table.html.erb, app/views/teams/index.html.erb
**READY**
NO
I have made some text modifications and CSS changes to reduce the table width.
Seems fine on my side but need to check on the production server.
Addresses #666
=> Modify Teams table contents and make CSS changes

.travis.yml, app/views/public_views/public_projects/_public_teams_table.html.erb
**READY**
NO
The PR aims to fix the links for the video and poster to reflect the latest Milestone submissions.
* Go to the Projects page by clicking on the Project section within the navbar
* Click on the blue button for any team and then click 'Watch Project Video' and 'View Project Poster' (if these buttons are present) respectively.
Resolves Issue #742
=> Get the latest milestone poster and video links

.travis.yml
**READY
NO
travis failing due to Could not find 'bundler' (1.16.2) required by your /home/travis/build/nusskylab/nusskylab/Gemfile.lock. (Gem::GemNotFoundException)
Add screenshot showing the current state of Skylab (in sync with the master branch)
* added   
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
to travis.yml
=> Fix travis bundler error

.travis.yml, app/views/advisers/_adviser_teams.html.erb, config/locales/en.yml
**READY**
NO
I make some minor changes by disabling adviser to click on dropped team and display as strikethrough text button. In addition, any future milestones peer evaluations will be considered disabled and strikethrough button.
(This is taken from the production website on 1 of the previous adviser which 1 of his/her team dropped from Orbital) 
Select any adviser's view all teams panel.
* #785
=> Show dropped teams as strikethrough text button at adviser home page

.travis.yml, app/views/teams/_team_form.html.erb, config/locales/simple_form.en.yml
**READY
NO
Removing the asterisks from the Advisor field and Status field from the team creation form.
- 
* Remove `required: true` attribute from f.input of :advisor_id and :status in the _team_form.html.erb
=> [iss771]The star before Adviser and Status in the team creation form should be removed.

app/views/public_views/public_projects/index.html.erb
**READY**
NO
Changed the default chosen level from Vostok to Apollo 11 when the project gallery webpage is first rendered. 
#770 
-
=> changed default level to apollo 11 in project gallery

.travis.yml, app/controllers/cohort_helper.rb, app/views/public_views/public_projects/_public_teams_table.html.erb
**READY**
NO
Updated the all_cohorts function to return an array from 2013 to the current year.
The project gallery now shows projects up to the current year.
*
=> #769 project gallery does not display 2020 cohort

app/views/public_views/public_staff/index.html.erb
**READY**
NO
- Move the side nav menu from the right to left.
- Replace the numerous button with a drop down button and place at top to make it obvious for user to see. (Some other pages that has multiple buttons below can benefit from using this change)
Head over to the public staff page.
* #795
=> Edit public staff page to remove cluttered button at the bottom of the page.

app/views/users/_users_table.html.erb, app/views/users/show.html.erb
YES 
2020 Skylab registration is done via Google forms, so the registration form on Skylab should be disabled.
Add screenshots to [summarize the UI changes (if any)]
Add screenshot showing the current state of Skylab (in sync with the master branch)
*
=> removed registration form

app/controllers/public_views/public_staff_controller.rb, app/models/facilitator.rb, app/views/public_views/public_staff/index.html.erb, app/views/public_views/public_staff/index.js.erb
**READY**
NO
Used AJAX to sort the facilitators base on time created, name and display order.
=> Reordering staff display

app/views/teams/_team_form.html.erb
Now admin can edit the project levels at ease.
Will further work into updated info by Dr. Zhao: "Perhaps it also make sense for the swap status to lock the editing even for the admins. But the lock should definitely not affect the team creation."
For details please refer to:
https://github.com/nusskylab/nusskylab/pull/784
=> Project-level-swap status now doesn't affect admins

registration/extractData.rb, registration/readme.md
**READY**
YES
* Ensure that repeated users with the same matric number will not be inserted into `STUDENTS` table.
* Users that are previously added as students will not be inserted into `STUDENTS` table.
* Add timestamps during creation of users
List related PRs against other branches: #807, #812, #813, #814 
Read readme.md
1. To check if all rows are inserted into their respective teams, run this on the DB (Change the 2500 to the respective team.id)
`SELECT teams.id, teams.team_name, users.user_name, users.matric_number FROM teams JOIN students ON teams.id= students.team_id JOIN users ON users.id=students.user_id WHERE teams.id >= 2500;`
Expected: The full list of 400 students with their teams
1. To check the total rows in the newly created teams, run this on the DB (Change the 2500 to …
=> Updates to Registration Script - Ignore duplicate users

registration/extractData.rb
**READY**
YES
* Ensure that repeated users with the same opennet number will not be inserted into `STUDENTS` table.
* Users that are previously added as students will not be inserted into `STUDENTS` table.
List related PRs against other branches: #807, #812, #813, #814, #815 
Read readme.md
1. To check if all rows are inserted into their respective teams, run this on the DB (Change the 2500 to the respective team.id)
`SELECT teams.id, teams.team_name, users.user_name, users.matric_number FROM teams JOIN students ON teams.id= students.team_id JOIN users ON users.id=students.user_id WHERE teams.id >= 2500;`
Expected: The full list of 400 students with their teams
1. To check the total rows in the newly created teams, run this on the DB (Change the 2500 to the respective team.id)
`SELECT …
=> Updates to Registration Script - Edit uniqueness criteria

registration/extractData.rb
**READY**
YES
* Ensure that repeated users with the same opennet number will not be inserted into `STUDENTS` table.
* Users that are previously added as students will not be inserted into `STUDENTS` table.
List related PRs against other branches: #807, #812, #813, #814, #815, #816  
Read readme.md
1. To check if all rows are inserted into their respective teams, run this on the DB (Change the 2500 to the respective team.id)
`SELECT teams.id, teams.team_name, users.user_name, users.matric_number FROM teams JOIN students ON teams.id= students.team_id JOIN users ON users.id=students.user_id WHERE teams.id >= 2500;`
Expected: The full list of 400 students with their teams
1. To check the total rows in the newly created teams, run this on the DB (Change the 2500 to the respective team.id) …
=> Updates to Registration Script -  Update student insertion

app/views/teams/_team_basic_info.html.erb, app/views/teams/_team_form.html.erb, config/initializers/devise.rb
**READY**
NO
Allow teams to update video link themselves. Fixed overflow problem if the link is too long. 
Only poster link
No wrap
Include video field
Text wrap
=> Allow teams to update video link

app/views/users/show.html.erb
The tab panel is missing the user roles tab. That is why we do not see the user roles tab.
**READY**
NO
I have added an additional tab for user roles which is missing from the tab panel.
1. Login using any account.
2. Head over to the user panel.
3. You should be able to see 2 tab: User details and User roles.
* #823
=> Add addition tab to the tab panel for user roles.

Gemfile, Gemfile.lock
YES | NO
This commit updates the jQuery version to 3.5.1 by updating the gem jquery-rails to 4.4.0.
Add screenshot showing the current state of Skylab (in sync with the master branch)
*
=> Update gem for jquery

app/views/public_views/public_projects/index.html.erb
**READY*
NO
Fix the error where the cohort tab in the project gallery is not automatically highlighted  upon fresh reload
* Close #851
=> Highlight cohort tab under project gallery upon fresh reload

app/views/public_views/public_projects/index.html.erb
**READY**
NO
Artemis was only introduced in 2020. The 'Artemis' tab in the project gallery should hence be hidden for cohorts before 2020.
Current Cohort 2019 (Artemis tab appears)
New Cohort 2019 (Artemis tab hidden)
New Cohort 2021 (unchanged)
- Resolves #838
=> Conditionally display Artemis tab in project gallery for cohorts after 2020

app/views/devise/shared/_links.html.erb
**READY**
YES
Since NUS retired OpenID in May, the signup By OpenID button should be removed.
*
=> Remove openid signup button

app/views/received_evals/index.html.erb
**READY**
NO
Based on different timing that an evaluator submits their feedback, one can determine who submitted which evaluation. Changed it such that private evaluations are only shown after the deadline of the submission.
Only one team submits their evaluation, the evaluated team can determine the team that submitted the private evaluation.
Private evaluations will only be shown after the submission deadline
* #831
=> Hide private evaluations before submission deadline
